<?php

use Twig\Environment;
use Twig\Error\LoaderError;
use Twig\Error\RuntimeError;
use Twig\Markup;
use Twig\Sandbox\SecurityError;
use Twig\Sandbox\SecurityNotAllowedTagError;
use Twig\Sandbox\SecurityNotAllowedFilterError;
use Twig\Sandbox\SecurityNotAllowedFunctionError;
use Twig\Source;
use Twig\Template;

/* default/layout/page.twig */
class __TwigTemplate_d8c01133dc0fb2f6ea020f274974f6077dbc9532c9c1809335db068af1aaabd8 extends \Twig\Template
{
    public function __construct(Environment $env)
    {
        parent::__construct($env);

        $this->blocks = [
            'frame' => [$this, 'block_frame'],
            'header' => [$this, 'block_header'],
            'content_header' => [$this, 'block_content_header'],
            'footer' => [$this, 'block_footer'],
        ];
    }

    protected function doGetParent(array $context)
    {
        // line 1
        return "layout/layout.twig";
    }

    protected function doDisplay(array $context, array $blocks = [])
    {
        $this->parent = $this->loadTemplate("layout/layout.twig", "default/layout/page.twig", 1);
        $this->parent->display($context, array_merge($this->blocks, $blocks));
    }

    // line 3
    public function block_frame($context, array $blocks = [])
    {
        // line 4
        echo "    <li><a href=\"";
        echo twig_escape_filter($this->env, $this->env->getExtension('Sami\Renderer\TwigExtension')->pathForStaticFile($context, "index.html"), "html", null, true);
        echo "\" target=\"_top\">Frames</a></li>
    <li><a href=\"#\" target=\"_top\">No Frames</a></li>
";
    }

    // line 8
    public function block_header($context, array $blocks = [])
    {
        // line 9
        echo "    <div class=\"header\">
        <ul>
            <li><a href=\"";
        // line 11
        echo twig_escape_filter($this->env, $this->env->getExtension('Sami\Renderer\TwigExtension')->pathForStaticFile($context, "classes.html"), "html", null, true);
        echo "\">Classes</a></li>
            ";
        // line 12
        if (($context["has_namespaces"] ?? $this->getContext($context, "has_namespaces"))) {
            // line 13
            echo "                <li><a href=\"";
            echo twig_escape_filter($this->env, $this->env->getExtension('Sami\Renderer\TwigExtension')->pathForStaticFile($context, "namespaces.html"), "html", null, true);
            echo "\">Namespaces</a></li>
            ";
        }
        // line 15
        echo "            <li><a href=\"";
        echo twig_escape_filter($this->env, $this->env->getExtension('Sami\Renderer\TwigExtension')->pathForStaticFile($context, "interfaces.html"), "html", null, true);
        echo "\">Interfaces</a></li>
            <li><a href=\"";
        // line 16
        echo twig_escape_filter($this->env, $this->env->getExtension('Sami\Renderer\TwigExtension')->pathForStaticFile($context, "traits.html"), "html", null, true);
        echo "\">Traits</a></li>
            <li><a href=\"";
        // line 17
        echo twig_escape_filter($this->env, $this->env->getExtension('Sami\Renderer\TwigExtension')->pathForStaticFile($context, "doc-index.html"), "html", null, true);
        echo "\">Index</a></li>
            ";
        // line 18
        $this->displayBlock("frame", $context, $blocks);
        echo "
        </ul>

        <div id=\"title\">";
        // line 21
        echo twig_escape_filter($this->env, $this->getAttribute(($context["project"] ?? $this->getContext($context, "project")), "config", [0 => "title"], "method"), "html", null, true);
        echo "</div>

        ";
        // line 23
        $this->displayBlock('content_header', $context, $blocks);
        // line 24
        echo "    </div>
";
    }

    // line 23
    public function block_content_header($context, array $blocks = [])
    {
        echo "";
    }

    // line 27
    public function block_footer($context, array $blocks = [])
    {
        // line 28
        echo "    <div id=\"footer\">
        Generated by <a href=\"http://sami.sensiolabs.org/\" target=\"_top\">Sami, the API Documentation Generator</a>.
    </div>
";
    }

    public function getTemplateName()
    {
        return "default/layout/page.twig";
    }

    public function isTraitable()
    {
        return false;
    }

    public function getDebugInfo()
    {
        return array (  112 => 28,  109 => 27,  103 => 23,  98 => 24,  96 => 23,  91 => 21,  85 => 18,  81 => 17,  77 => 16,  72 => 15,  66 => 13,  64 => 12,  60 => 11,  56 => 9,  53 => 8,  45 => 4,  42 => 3,  32 => 1,);
    }

    /** @deprecated since 1.27 (to be removed in 2.0). Use getSourceContext() instead */
    public function getSource()
    {
        @trigger_error('The '.__METHOD__.' method is deprecated since version 1.27 and will be removed in 2.0. Use getSourceContext() instead.', E_USER_DEPRECATED);

        return $this->getSourceContext()->getCode();
    }

    public function getSourceContext()
    {
        return new Source("{% extends \"layout/layout.twig\" %}

{% block frame %}
    <li><a href=\"{{ path('index.html') }}\" target=\"_top\">Frames</a></li>
    <li><a href=\"#\" target=\"_top\">No Frames</a></li>
{% endblock %}

{% block header %}
    <div class=\"header\">
        <ul>
            <li><a href=\"{{ path('classes.html') }}\">Classes</a></li>
            {% if has_namespaces %}
                <li><a href=\"{{ path('namespaces.html') }}\">Namespaces</a></li>
            {% endif %}
            <li><a href=\"{{ path('interfaces.html') }}\">Interfaces</a></li>
            <li><a href=\"{{ path('traits.html') }}\">Traits</a></li>
            <li><a href=\"{{ path('doc-index.html') }}\">Index</a></li>
            {{ block('frame') }}
        </ul>

        <div id=\"title\">{{ project.config('title') }}</div>

        {% block content_header '' %}
    </div>
{% endblock %}

{% block footer %}
    <div id=\"footer\">
        Generated by <a href=\"http://sami.sensiolabs.org/\" target=\"_top\">Sami, the API Documentation Generator</a>.
    </div>
{% endblock %}
", "default/layout/page.twig", "/projects/Sami-1.4.1/Sami/Resources/themes/default/layout/page.twig");
    }
}
