name: CI

on:
    push: ~
    pull_request: ~
    release:
        types: [created]
    workflow_dispatch: ~

jobs:
    tests:
        runs-on: ubuntu-latest

        name: "PHP ${{ matrix.php }}"

        strategy:
            fail-fast: false
            matrix:
                php: [7.1, 7.2, 7.3, 7.4, 8.0]

        steps:
            -
                name: Install FFMpeg
                run: sudo apt-get install ffmpeg

            -
                uses: actions/checkout@v2

            -
                name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: "${{ matrix.php }}"
                    coverage: xdebug

            -
                name: Install PHP dependencies
                run: composer install --no-interaction --prefer-source

            -
                name: Run analysis
                run: composer validate --strict

            -
                name: Run PHPUnit
                run: vendor/bin/phpunit --coverage-clover clover.xml

            -
                name: Send coverage report
                if: github.repository == 'PHP-FFMpeg/PHP-FFMpeg'
                run: |
                    wget https://scrutinizer-ci.com/ocular.phar
                    php ocular.phar code-coverage:upload --format=php-clover clover.xml
